---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```


```{r}
dialogue <- c("小明說：'上課要認真。'",
               "小花說：'我也覺得'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
studentMajors <- factor(
  c("歷史系", "經濟系", "法律系")
)
```
```{r}
studentMajors0 <-  c("歷史系", "經濟系", "法律系")

```
```{r}
class(studentMajors)
```

```{r}
class(studentMajors0)
```
```{r}
typeof(studentMajors)
typeof(studentMajors0)
```
```{r}
birthplace <- factor(
  c("台中市", "台中市", "台北市", "台北市", "台北市")
)
typeof(birthplace)

levels(birthplace
       )
as.integer(birthplace)
```
```{r}
library(lubridate)
dtObject <- ymd_hms("1970-01-01 00:02:53") 
dtObjectVector <- ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
class(dtObject)
dtObject
typeof(dtObject)
levels(dtObject)
as.integer(dtObject)
as.double(dtObject)
```







