---
title: '2019-05-29'
author: "林茂廷"
date: "05/29/2019"
output: html_document
---


```{r}
library(lubridate)
now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```
```{r}
now2()
now2() ->xx
```

```{r}
browseURL("https://www.ntpu.edu.tw")
```
```{r}
textbookURL <- function(){browseURL("https://www.ntpu.edu.tw")}
textbookURL()
```

```{r}

library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```
創造一個demand_supply_fun(P,a,b,c,d)，它會輸出一個list包含三個元素：供給量，需求量，超額供給量
```{r}


demand_supply_fun <- function(P,a,b,c,d){
  supply_fun <- a+b*P
  demand_fun <- c-d*P
  more <- supply_fun-demand_fun
  return(list('供給量'=supply_fun,
              '需求量'=demand_fun,
              '超額供給量'=more))
}


```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```
```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs)
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```
```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```
修改範例2的gpa_fun, 若輸入學號不存在則在螢幕顯示“查無此學號”。
```{r}

gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  subSample <- transcriptDataFinal[logiChosenStudent,]
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
  }
  else
    {
      message("查無此學號")
    }
}
gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```
```{r}

gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID %in% transcriptDataFinal$學號)
  {return(GPA)}
  else{message("查無此學號")}
}
gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號

```
```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P必需大於等於",-a/b,"(即-a/b值)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
fizzbuzz<-function(a){

  if(a%%3==0 & a%%5==0)
    {print("fizzbuzz")}
  else if(a%%3==0)
     {print("fizz")}
  else if(a%%5==0)
     {print("buzz")}
  else{print(a)}
 }
```

```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
if(a>2) {
  print("a大於2")
}
```

```{r}
a>2
all(a>2)
```

```{r}
a>2
any(a>2)
```

